### get all employees
GET http://localhost:3000/employees

### get one employee

GET http://localhost:3000/employees/5

### create employee

POST http://localhost:3000/employees
content-type:application/json

{
    "name":"employee7",
    "phone":987654327,
    "email":"cba7@gmail.com",
    "tasks":[{"name":"task6-7"},{"name":"task8-7"}],
    "meetings":[{"zoomUrl":"meeting7-7"},{"zoomUrl":"meeting9-7"}] 
}

### update employee

PATCH http://localhost:3000/employees/4
Content-Type: application/json

{
    "name":"employee4"
}

### delete employee
DELETE http://localhost:3000/employees/4

